name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull turborvip/nestjs-initial:latest
    - name: Delete Old docker container
      run: sudo docker rm -f nestjs-initial-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3788:6575 --name nestjs-initial-container turborvip/nestjs-initial-image