name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    # steps:
    # - name: Stop Docker Container
    #   run: sudo docker stop nestjs-template-ver1
    # - name: Delete Docker Container
    #   run: sudo docker system prune -af --volumes
    # - name: Pull Docker image
    #   run: sudo docker pull turborvip/nestjs-template-ver1:latest 
    # - name: Run Docker Container
    #   run: sudo docker run -d -p 3788:6575 --name nestjs-template-ver1 turborvip/nestjs-template-ver1:latest
    # - name: Docker-compose up
    #   run: sudo docker-compose up -d